/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTL;

import java.io.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import java.util.*;
/**
 *
 * @author Administrator
 */
public class AddRule extends javax.swing.JFrame {

    /**
     * Creates new form AddRule
     */
    MainGUI mainGUI;
    public AddRule(MainGUI parent) {
        initComponents();
        mainGUI = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTypeRule = new javax.swing.JComboBox();
        cbCondition1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCondition2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbResult = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spCF = new javax.swing.JSpinner();
        lbTypeRule = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btAddRule = new javax.swing.JButton();

        setTitle("Thêm luật mới");
        setResizable(false);

        cbTypeRule.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Luật đơn", "Luật And", "Luật Or" }));
        cbTypeRule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTypeRuleItemStateChanged(evt);
            }
        });
        cbTypeRule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTypeRuleMouseClicked(evt);
            }
        });
        cbTypeRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeRuleActionPerformed(evt);
            }
        });

        jLabel1.setText("Chọn loại luật");

        jLabel2.setText("Điều kiện");

        cbCondition2.setEnabled(false);

        jLabel3.setText("Điều kiện thứ hai");

        jLabel4.setText("Kết luận");

        jLabel5.setText("Độ tin cậy");

        spCF.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(-1.0f), Float.valueOf(1.0f), Float.valueOf(0.01f)));

        jLabel7.setText("IF");

        jLabel6.setText("THEN");

        btAddRule.setText("Thêm luật");
        btAddRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddRuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(48, 48, 48)
                        .addComponent(cbTypeRule, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbResult, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCondition1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addComponent(lbTypeRule, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbCondition2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spCF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(btAddRule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTypeRule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCondition2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTypeRule, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCondition1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(spCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btAddRule)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTypeRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeRuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeRuleActionPerformed

    private void cbTypeRuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTypeRuleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeRuleMouseClicked

    private void cbTypeRuleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTypeRuleItemStateChanged
        // TODO add your handling code here:
        String sRule = (String)cbTypeRule.getSelectedItem();
        if (sRule.equals("Luật đơn"))
        {
            lbTypeRule.setText("");
            cbCondition2.setEnabled(false);
        }
        if (sRule.equals("Luật And"))
        {
            lbTypeRule.setText("AND");
            cbCondition2.setEnabled(true);
        }
        if (sRule.equals("Luật Or"))
        {
            lbTypeRule.setText("OR");
            cbCondition2.setEnabled(true);
        }
    }//GEN-LAST:event_cbTypeRuleItemStateChanged

    private boolean AddSingleRule(int nIDCondition, int nIDResult, float dCF)
    {
        String stream;
        SingleRule ruleSingle;
        FileOutputStream fileOut;
        PrintWriter printFile;
        
        ruleSingle = new SingleRule(nIDCondition, nIDResult, dCF);
        if (!mainGUI.listSingleRule.add(ruleSingle))
        {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm luật vào bộ nhớ", "Lỗi", INFORMATION_MESSAGE);            
            return false;
        }
        
        try
        {
            fileOut = new FileOutputStream("src\\KB\\SingleRule.txt", true);//true để ghi tiếp vào file 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Không tìm thấy tệp luật đơn", "Lỗi ghi luật vào cơ sở tri thức", ERROR_MESSAGE);
            return false;
        }
        
        printFile = new PrintWriter(fileOut);
        
        stream = "\r\n" 
                + ruleSingle.nIDCondition + "|" 
                + ruleSingle.nIDResult + "|" 
                + ruleSingle.CF
                + "\r\n";
        printFile.write(stream);
        printFile.close();
        
        return true;
    }
    
    private boolean AddAndRule(int nIDCondition1, int nIDCondition2, int nIDResult, float dCF)
    {
        String stream;
        AndRule ruleAnd;
        FileOutputStream fileOut;
        PrintWriter printFile;
        
        ruleAnd = new AndRule(nIDCondition1, nIDCondition2, nIDResult, dCF);
        if (!mainGUI.listAndRule.add(ruleAnd))
        {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm luật vào bộ nhớ", "Lỗi", INFORMATION_MESSAGE);            
            return false;
        }
        
        try
        {
            fileOut = new FileOutputStream("src\\KB\\AndRule.txt", true);//true để ghi tiếp vào file 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Không tìm thấy tệp luật And", "Lỗi ghi luật vào cơ sở tri thức", ERROR_MESSAGE);
            return false;
        }
        
        printFile = new PrintWriter(fileOut);
        
        stream = "\r\n" 
                + ruleAnd.nIDCondition1 + "|" 
                + ruleAnd.nIDCondition2 + "|" 
                + ruleAnd.nIDResult + "|" 
                + ruleAnd.CF
                + "\r\n";
        printFile.write(stream);
        printFile.close();
        
        return true;
    }
    private boolean AddOrRule(int nIDCondition1, int nIDCondition2, int nIDResult, float dCF)
    {
        String stream;
        OrRule ruleOr;
        FileOutputStream fileOut;
        PrintWriter printFile;
        
        ruleOr = new OrRule(nIDCondition1, nIDCondition2, nIDResult, dCF);
        if (!mainGUI.listOrRule.add(ruleOr))
        {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm luật vào bộ nhớ", "Lỗi", INFORMATION_MESSAGE);            
            return false;
        }
        
        try
        {
            fileOut = new FileOutputStream("src\\KB\\OrRule.txt", true);//true để ghi tiếp vào file 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Không tìm thấy tệp luật Or", "Lỗi ghi luật vào cơ sở tri thức", ERROR_MESSAGE);
            return false;
        }
        
        printFile = new PrintWriter(fileOut);
        
        stream = "\r\n" 
                + ruleOr.nIDCondition1 + "|" 
                + ruleOr.nIDCondition2 + "|" 
                + ruleOr.nIDResult + "|" 
                + ruleOr.CF
                + "\r\n";
        printFile.write(stream);
        printFile.close();
        
        return true;
    }
    private void btAddRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddRuleActionPerformed
        // TODO add your handling code here:
        int nIDCondition1, nIDCondition2, nIDResult;
        String s, sRule;
        int nIndex;
        float dCF;
        
        s = (String)cbCondition1.getSelectedItem();
        if ((s == null) || (s.isEmpty()))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn điều kiện", "Lỗi", INFORMATION_MESSAGE);
            return;
        }
        nIDCondition1 = Integer.parseInt(s.substring(0, s.indexOf('|')));
        
        sRule = (String)cbTypeRule.getSelectedItem();
        if (sRule.equals("Luật đơn"))
        {
            nIDCondition2 = -1;
        }
        else
        {
            s = (String)cbCondition2.getSelectedItem();
            if ((s == null) || (s.isEmpty()))
            {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dủ điều kiện", "Lỗi", INFORMATION_MESSAGE);
                return;
            }
            nIDCondition2 = Integer.parseInt(s.substring(0, s.indexOf('|')));
        }
        
        s = (String)cbResult.getSelectedItem();
        if ((s == null) || (s.isEmpty()))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn kết luận", "Lỗi", INFORMATION_MESSAGE);
            return;
        }
        nIDResult = Integer.parseInt(s.substring(0, s.indexOf('|')));
        
        dCF = (float) spCF.getValue();
        
        if (sRule.equals("Luật đơn"))
        {
            AddSingleRule(nIDCondition1, nIDResult, dCF);
        }
        if (sRule.equals("Luật And"))
        {
            AddAndRule(nIDCondition1, nIDCondition2, nIDResult, dCF);
        }
        if (sRule.equals("Luật Or"))
        {
            AddOrRule(nIDCondition1, nIDCondition2, nIDResult, dCF);
        }
    }//GEN-LAST:event_btAddRuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRule(new MainGUI()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddRule;
    private javax.swing.JComboBox cbCondition1;
    private javax.swing.JComboBox cbCondition2;
    private javax.swing.JComboBox cbResult;
    private javax.swing.JComboBox cbTypeRule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbTypeRule;
    private javax.swing.JSpinner spCF;
    // End of variables declaration//GEN-END:variables
}
